/*
 * AssemblerHW4Q1a.asm
 *
 *  Created: 4/10/2019 1:51:43 PM
 *   Author: Alireza
 */ 
.DEF OUTER=R19
.DEF INNER=R20
.DEF CNT=R21
.DEF FLAG=R22
.DEF TEMP = R25
.DEF CHAR_PREV = R26
JMP RESET
 
 
RESET:
 NOP;CLR LOOPCNT 
 
 BCDTO7_SEG: .DB 0X3F,0X06,0X5B,0X4F,0X66,0X6D,0X7D,0X07,0X7F,0X6F

 SER TEMP;
 OUT DDRB, TEMP
;SETTING INPUT/OUTPUT PORTS
ANDI R17, (0 << PD3) | (0 << PD6);INPUT
ORI R17, (1 << PD4) | (1 << PD5);OUTPUT
OUT DDRD, R17
ORI R18, (1 << PD3) | (1 << PD6);PULL UP
OUT PORTD, R18
LDI CNT, 0

JMP MAIN

MAIN:
CALL MAIN_A
CALL MAIN_B  
CALL MAIN_C
JMP MAIN

MAIN_A:

SBIC PIND, PD3;SKIP IF SWITCH PRESSED 
CBI PORTD, PD5;TURN OFF LED1
SBIS PIND, PD3;SKIP IF SWITCH RELEASED
SBI PORTD, PD5;TURN ON LED1
RET

MAIN_B:
CPI CNT, 1
BREQ AFTER
SBIS PIND, PD6;SKIP IF SW2 RELEASED
CALL BLINK_5_TIMES


AFTER:
SBIC PIND, PD6;SKIP IF SW2 PRESSED
LDI CNT, 0

RET

DELAY_HALF_SEC:
LDI OUTER, 230;OUTER LOOP VARIABLE
LDI INNER, 230;INNER LOOP VARIABLE
OUTER_LOOP:
 CALL NOP_DELAY
 DEC OUTER
 CPI OUTER, 0
 BREQ CONTINUE
 LDI INNER, 200
 INNER_LOOP:
   CALL NOP_DELAY
   DEC INNER
   CPI INNER, 0
   BREQ OUTER_LOOP 
 JMP INNER_LOOP
 
JMP OUTER_LOOP
CONTINUE:
RET

NOP_DELAY:
NOP
NOP
NOP
NOP
NOP
NOP
NOP
NOP
NOP
NOP
NOP
NOP
NOP
NOP
NOP
NOP
NOP
NOP
NOP
NOP
NOP
NOP
NOP
NOP
NOP
NOP
NOP
NOP
NOP
RET

BLINK_5_TIMES:
LDI CNT, 5
BLINK_5_TIMES_LOOP:
;TURN LED ON
SBI PORTD, PD4
CALL DELAY_HALF_SEC
;TURN LED OFF 
CBI PORTD, PD4
CALL DELAY_HALF_SEC
DEC CNT
CPI CNT,0
BRNE BLINK_5_TIMES_LOOP
LDI CNT, 1
RET


MAIN_C:
 LDI ZH, HIGH(BCDTO7_SEG)
 LDI ZL, LOW(BCDTO7_SEG)
 ADIW Z, 3;NOW Z POINTS TO THE FIRST MEANINGFUL ELEMENT OF THE ARRAY, WHICH IS THE FIRST CHARACTER
 ;THE FOLLOWING ADIW Z, X INSTRUCTION TESTS WHETHER THE NUMBER X APPEARS CORRECTLY ON THE 7-SEGMENT OR NOT
 ADIW Z,7
 
 LPM CHAR_PREV, Z
 OUT PORTB, CHAR_PREV

RET