/*
 * AssemblerHW4Q1c.asm
 *
 *  Created: 4/11/2019 5:06:42 PM
 *   Author: Alireza
 */ 

/*
 * AssemblerHW3Q5.asm
 *
 *  Created: 3/23/2019 7:28:22 PM
 *   Author: Alireza
 */ 

 .def TEMP = R29
 .def CHAR_PREV = R30
 
RESET:
 NOP;CLR LOOPCNT 
 
 BCDTO7_SEG: .DB 0X3F,0X06,0X5B,0X4F,0X66,0X6D,0X7D,0X07,0X7F,0X6F
 ;THE FOLLOWING ARRAY IS NEITHER ASCENDING NOR DESCENDING
 ;ARRAY: .DB "TRSQPONMLKJIHGFEDCBA"
 
 SER TEMP;
 OUT DDRB, TEMP
 NOP;CLR STATUS	
 JMP MAIN

MAIN: 

 LDI ZH, HIGH(BCDTO7_SEG)
 LDI ZL, LOW(BCDTO7_SEG)
 ADIW Z, 1;NOW Z POINTS TO THE FIRST MEANINGFUL ELEMENT OF THE ARRAY, WHICH IS THE FIRST CHARACTER
 ;THE FOLLOWING ADIW Z, X INSTRUCTION TESTS WHETHER THE NUMBER X APPEARS CORRECTLY ON THE 7-SEGMENT OR NOT
 ADIW Z, 5
 ;LDI STATUS, 0X01;WE ASSUME IT'S ASCENDING AT THE FIRST GLANCE

 LPM CHAR_PREV, Z
 OUT PORTB, CHAR_PREV

 JMP MAIN