/*
 * AssemblerHW4Q2b.asm
 *
 *  Created: 4/11/2019 5:54:19 PM
 *   Author: Alireza
 */
.DEF WDT = R27   
.DEF HLP = R22
JMP RESET

RESET:
;SETTING INPUT/OUTPUT PORTS
ANDI R17, (0 << PD3) | (0 << PD6);INPUT
ORI R17, (1 << PD4) | (1 << PD5);OUTPUT
OUT DDRD, R17
ORI R18, (1 << PD3) | (1 << PD6);PULL UP
OUT PORTD, R18
LDI R23, 0
JMP MAIN

MAIN:

SBIC PIND, PD3;SKIP IF SW1 PRESSED 
LDI HLP, 0




SBIS PIND, PD3;SKIP IF SW1 RELEASED
LDI HLP, 1

CPI HLP, 0;
BRNE MAIN
;IF WE ARE HERE, WE ARE CERTAIN ABOUT HAVING RELEASED SW1
JMP WAIT



WAIT:
SBIS PIND, D3;SKIP IF SW1 RELEASED
LDI R23, 1
CPI R23, 1
BRNE WAIT

;ENABLING WATCHDOG TIMER, SETTING 2.1S AS THE TIMEOUT
LDI WDT, (1 << WDE) | (1 << WDP2) | (1 << WDP1) | (1 << WDP0)
OUT WDTCR, WDT

SBI PIND, PD5;TURN ON LED1
JMP TURN_LED_ON

TURN_LED_ON:
SBIS PIND, PD6;SKIP IF SW2 RELEASED
WDR
JMP TURN_LED_ON
